export interface Language {
  code: string;
  name: string;
  nativeName: string;
}

export interface Country {
  code: string;
  name: string;
  flag: string;
}

export const LANGUAGES: Language[] = [
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'it', name: 'Italian', nativeName: 'Italiano' },
  { code: 'es', name: 'Spanish', nativeName: 'Espanol' },
  { code: 'fr', name: 'French', nativeName: 'Francais' },
  { code: 'de', name: 'German', nativeName: 'Deutsch' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Portugues' },
  { code: 'nl', name: 'Dutch', nativeName: 'Nederlands' },
  { code: 'pl', name: 'Polish', nativeName: 'Polski' },
  { code: 'sv', name: 'Swedish', nativeName: 'Svenska' },
  { code: 'da', name: 'Danish', nativeName: 'Dansk' },
  { code: 'fi', name: 'Finnish', nativeName: 'Suomi' },
  { code: 'no', name: 'Norwegian', nativeName: 'Norsk' },
  { code: 'cs', name: 'Czech', nativeName: 'Cestina' },
  { code: 'hu', name: 'Hungarian', nativeName: 'Magyar' },
  { code: 'ro', name: 'Romanian', nativeName: 'Romana' },
  { code: 'el', name: 'Greek', nativeName: 'Ellinika' },
  { code: 'tr', name: 'Turkish', nativeName: 'Turkce' },
  { code: 'ru', name: 'Russian', nativeName: 'Russkij' },
  { code: 'uk', name: 'Ukrainian', nativeName: 'Ukrainska' },
  { code: 'bg', name: 'Bulgarian', nativeName: 'Balgarski' },
  { code: 'hr', name: 'Croatian', nativeName: 'Hrvatski' },
  { code: 'sk', name: 'Slovak', nativeName: 'Slovencina' },
  { code: 'sl', name: 'Slovenian', nativeName: 'Slovenscina' },
  { code: 'et', name: 'Estonian', nativeName: 'Eesti' },
  { code: 'lv', name: 'Latvian', nativeName: 'Latviesu' },
  { code: 'lt', name: 'Lithuanian', nativeName: 'Lietuviu' },
  { code: 'ja', name: 'Japanese', nativeName: 'Nihongo' },
  { code: 'ko', name: 'Korean', nativeName: 'Hangugeo' },
  { code: 'zh', name: 'Chinese', nativeName: 'Zhongwen' },
  { code: 'ar', name: 'Arabic', nativeName: 'Al-Arabiyya' },
  { code: 'he', name: 'Hebrew', nativeName: 'Ivrit' },
  { code: 'hi', name: 'Hindi', nativeName: 'Hindi' },
  { code: 'th', name: 'Thai', nativeName: 'Phasa Thai' },
  { code: 'vi', name: 'Vietnamese', nativeName: 'Tieng Viet' },
  { code: 'id', name: 'Indonesian', nativeName: 'Bahasa Indonesia' },
  { code: 'ms', name: 'Malay', nativeName: 'Bahasa Melayu' },
];

export const COUNTRIES: Country[] = [
  { code: 'AF', name: 'Afghanistan', flag: 'AF' },
  { code: 'AL', name: 'Albania', flag: 'AL' },
  { code: 'DZ', name: 'Algeria', flag: 'DZ' },
  { code: 'AD', name: 'Andorra', flag: 'AD' },
  { code: 'AO', name: 'Angola', flag: 'AO' },
  { code: 'AR', name: 'Argentina', flag: 'AR' },
  { code: 'AM', name: 'Armenia', flag: 'AM' },
  { code: 'AU', name: 'Australia', flag: 'AU' },
  { code: 'AT', name: 'Austria', flag: 'AT' },
  { code: 'AZ', name: 'Azerbaijan', flag: 'AZ' },
  { code: 'BS', name: 'Bahamas', flag: 'BS' },
  { code: 'BH', name: 'Bahrain', flag: 'BH' },
  { code: 'BD', name: 'Bangladesh', flag: 'BD' },
  { code: 'BY', name: 'Belarus', flag: 'BY' },
  { code: 'BE', name: 'Belgium', flag: 'BE' },
  { code: 'BZ', name: 'Belize', flag: 'BZ' },
  { code: 'BJ', name: 'Benin', flag: 'BJ' },
  { code: 'BT', name: 'Bhutan', flag: 'BT' },
  { code: 'BO', name: 'Bolivia', flag: 'BO' },
  { code: 'BA', name: 'Bosnia and Herzegovina', flag: 'BA' },
  { code: 'BW', name: 'Botswana', flag: 'BW' },
  { code: 'BR', name: 'Brazil', flag: 'BR' },
  { code: 'BN', name: 'Brunei', flag: 'BN' },
  { code: 'BG', name: 'Bulgaria', flag: 'BG' },
  { code: 'KH', name: 'Cambodia', flag: 'KH' },
  { code: 'CM', name: 'Cameroon', flag: 'CM' },
  { code: 'CA', name: 'Canada', flag: 'CA' },
  { code: 'CL', name: 'Chile', flag: 'CL' },
  { code: 'CN', name: 'China', flag: 'CN' },
  { code: 'CO', name: 'Colombia', flag: 'CO' },
  { code: 'CR', name: 'Costa Rica', flag: 'CR' },
  { code: 'HR', name: 'Croatia', flag: 'HR' },
  { code: 'CU', name: 'Cuba', flag: 'CU' },
  { code: 'CY', name: 'Cyprus', flag: 'CY' },
  { code: 'CZ', name: 'Czech Republic', flag: 'CZ' },
  { code: 'DK', name: 'Denmark', flag: 'DK' },
  { code: 'DO', name: 'Dominican Republic', flag: 'DO' },
  { code: 'EC', name: 'Ecuador', flag: 'EC' },
  { code: 'EG', name: 'Egypt', flag: 'EG' },
  { code: 'SV', name: 'El Salvador', flag: 'SV' },
  { code: 'EE', name: 'Estonia', flag: 'EE' },
  { code: 'ET', name: 'Ethiopia', flag: 'ET' },
  { code: 'FI', name: 'Finland', flag: 'FI' },
  { code: 'FR', name: 'France', flag: 'FR' },
  { code: 'GE', name: 'Georgia', flag: 'GE' },
  { code: 'DE', name: 'Germany', flag: 'DE' },
  { code: 'GH', name: 'Ghana', flag: 'GH' },
  { code: 'GR', name: 'Greece', flag: 'GR' },
  { code: 'GT', name: 'Guatemala', flag: 'GT' },
  { code: 'HN', name: 'Honduras', flag: 'HN' },
  { code: 'HK', name: 'Hong Kong', flag: 'HK' },
  { code: 'HU', name: 'Hungary', flag: 'HU' },
  { code: 'IS', name: 'Iceland', flag: 'IS' },
  { code: 'IN', name: 'India', flag: 'IN' },
  { code: 'ID', name: 'Indonesia', flag: 'ID' },
  { code: 'IR', name: 'Iran', flag: 'IR' },
  { code: 'IQ', name: 'Iraq', flag: 'IQ' },
  { code: 'IE', name: 'Ireland', flag: 'IE' },
  { code: 'IL', name: 'Israel', flag: 'IL' },
  { code: 'IT', name: 'Italy', flag: 'IT' },
  { code: 'JM', name: 'Jamaica', flag: 'JM' },
  { code: 'JP', name: 'Japan', flag: 'JP' },
  { code: 'JO', name: 'Jordan', flag: 'JO' },
  { code: 'KZ', name: 'Kazakhstan', flag: 'KZ' },
  { code: 'KE', name: 'Kenya', flag: 'KE' },
  { code: 'KR', name: 'South Korea', flag: 'KR' },
  { code: 'KW', name: 'Kuwait', flag: 'KW' },
  { code: 'LV', name: 'Latvia', flag: 'LV' },
  { code: 'LB', name: 'Lebanon', flag: 'LB' },
  { code: 'LY', name: 'Libya', flag: 'LY' },
  { code: 'LI', name: 'Liechtenstein', flag: 'LI' },
  { code: 'LT', name: 'Lithuania', flag: 'LT' },
  { code: 'LU', name: 'Luxembourg', flag: 'LU' },
  { code: 'MY', name: 'Malaysia', flag: 'MY' },
  { code: 'MT', name: 'Malta', flag: 'MT' },
  { code: 'MX', name: 'Mexico', flag: 'MX' },
  { code: 'MD', name: 'Moldova', flag: 'MD' },
  { code: 'MC', name: 'Monaco', flag: 'MC' },
  { code: 'MN', name: 'Mongolia', flag: 'MN' },
  { code: 'ME', name: 'Montenegro', flag: 'ME' },
  { code: 'MA', name: 'Morocco', flag: 'MA' },
  { code: 'NP', name: 'Nepal', flag: 'NP' },
  { code: 'NL', name: 'Netherlands', flag: 'NL' },
  { code: 'NZ', name: 'New Zealand', flag: 'NZ' },
  { code: 'NI', name: 'Nicaragua', flag: 'NI' },
  { code: 'NG', name: 'Nigeria', flag: 'NG' },
  { code: 'NO', name: 'Norway', flag: 'NO' },
  { code: 'OM', name: 'Oman', flag: 'OM' },
  { code: 'PK', name: 'Pakistan', flag: 'PK' },
  { code: 'PA', name: 'Panama', flag: 'PA' },
  { code: 'PY', name: 'Paraguay', flag: 'PY' },
  { code: 'PE', name: 'Peru', flag: 'PE' },
  { code: 'PH', name: 'Philippines', flag: 'PH' },
  { code: 'PL', name: 'Poland', flag: 'PL' },
  { code: 'PT', name: 'Portugal', flag: 'PT' },
  { code: 'QA', name: 'Qatar', flag: 'QA' },
  { code: 'RO', name: 'Romania', flag: 'RO' },
  { code: 'RU', name: 'Russia', flag: 'RU' },
  { code: 'SA', name: 'Saudi Arabia', flag: 'SA' },
  { code: 'RS', name: 'Serbia', flag: 'RS' },
  { code: 'SG', name: 'Singapore', flag: 'SG' },
  { code: 'SK', name: 'Slovakia', flag: 'SK' },
  { code: 'SI', name: 'Slovenia', flag: 'SI' },
  { code: 'ZA', name: 'South Africa', flag: 'ZA' },
  { code: 'ES', name: 'Spain', flag: 'ES' },
  { code: 'LK', name: 'Sri Lanka', flag: 'LK' },
  { code: 'SE', name: 'Sweden', flag: 'SE' },
  { code: 'CH', name: 'Switzerland', flag: 'CH' },
  { code: 'TW', name: 'Taiwan', flag: 'TW' },
  { code: 'TH', name: 'Thailand', flag: 'TH' },
  { code: 'TN', name: 'Tunisia', flag: 'TN' },
  { code: 'TR', name: 'Turkey', flag: 'TR' },
  { code: 'UA', name: 'Ukraine', flag: 'UA' },
  { code: 'AE', name: 'United Arab Emirates', flag: 'AE' },
  { code: 'GB', name: 'United Kingdom', flag: 'GB' },
  { code: 'US', name: 'United States', flag: 'US' },
  { code: 'UY', name: 'Uruguay', flag: 'UY' },
  { code: 'UZ', name: 'Uzbekistan', flag: 'UZ' },
  { code: 'VE', name: 'Venezuela', flag: 'VE' },
  { code: 'VN', name: 'Vietnam', flag: 'VN' },
];

export function getFlagEmoji(countryCode: string): string {
  const codePoints = countryCode
    .toUpperCase()
    .split('')
    .map((char) => 127397 + char.charCodeAt(0));
  return String.fromCodePoint(...codePoints);
}

export function getLanguageByCode(code: string): Language | undefined {
  return LANGUAGES.find((l) => l.code === code);
}

export function getCountryByCode(code: string): Country | undefined {
  return COUNTRIES.find((c) => c.code === code);
}
